[project]
name = "together-ai-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "pydantic>=2.11.4",
    "together>=1.5.6",
    "uvicorn>=0.34.2",
]
